### PR TITLE
Commented out all the empty links

### PR DESCRIPTION
**Pull request by sthaeling**
Commented out the empty links in contact.html, events.html, index.html, magazine.html, sponsors.html, team.html page.

Furthermore commented out the list and lists elements formerly containing the empty links.

### CODE REVIEW

**Comment by thesohelshaikh** [comment]
This messes up the logo.

**Comment by sthaeling** [comment]
In what way does it mess up the logo? It only seems to get bigger or smaller.

**Comment by thesohelshaikh** [comment]
If you could try and keep the logo of the same size. 

Alternatively, keep the 4 sections(Events, Explore, resources, about) with just one link. I will update the paths for them later.

**Comment by sthaeling** [comment]
Added Commit with changes. Now each section has one leftover link.

**Comment by thesohelshaikh** [comment]
Main page has a different footer.

**Pull request merged**
